### PR TITLE
Add documentation for automatic installation of supported middlewares

### PR DESCRIPTION
**Pull request by severin-lemaignan**

### CODE REVIEW

**Comment by adegroote** [comment]
I think that we need to keep the warning about non-installed middleware for morse <= 1.3 (as it won't hit ubuntu before 15.10 and Debian before, well, I don't know :D).

Moreover, we need to cross check with Sylvestre that it is ok for Debian to include all stuff, even stuff which need additional, non-packaged runtime depds (otherwise the whole effort is a bit useless).

**Comment by severin-lemaignan** [comment]
Yes, it's a big and important warning to add. I've been thinking about that too this morning. I'll also check with Sylvestre for the Debian packaging.

**Comment by severin-lemaignan** [comment]
Ok, Sylvestre gives us green light.

**Comment by severin-lemaignan** [comment]
I've added warning for distribution packaging MORSE 1.2.2 to the PR

**Comment by adegroote** [comment]
Merged in main repository.

**Pull request closed without merging**
