### PR TITLE
[builder] workaround numpy.core.multiarray missmatch

### PR DESCRIPTION
**Pull request by PierrickKoch**

### CODE REVIEW

**Comment by adegroote** [comment]
Do you have any time to work on it ?

**Comment by pierriko** [comment]
the "conclusion" on bf-python@blender.org was "use Blender's numpy", so I guess this workaround can go in master for a litle while untill we find something cleaner.

**Comment by pierriko** [comment]
the problem is that it breaks the current travis setup because of python3.4 from blender ppa / python3-numpy from ubuntu (3.2).
but I can work on that.

**Comment by pierriko** [comment]
https://travis-ci.org/pierriko/morse/builds/71414059 should be good

**Comment by adegroote** [comment]
Thanks.  Do you consider https://github.com/pierriko/morse/commit/ca01ea291123bdce3cd49fee0b9c4bb909dec307#commitcomment-11740773 ?

**Comment by adegroote** [comment]
Merged

**Pull request closed without merging**
